---
title: "LGI Exploratory"
---

```{r}
#| label: set up
#| include: false
#| message: false
# Import Libraries
library(tidyverse)
library(janitor)
library(mgcv)

# Source
source("R/plotting.R")
source("R/reporting.R")

# Define Paths
dir_dataset <- file.path(
  "/", "data", "secure", "bit_repo", "projects_repo", "ExtraLong", "data",
  "dataset_pnc_cross"
)

dir_evolpsy <- file.path(
  "/", "data", "secure", "bit_repo", "pi_repo", "raquel_gur", "evolpsy", "data"
)

path_imaging <- file.path(dir_dataset, "imaging_data.csv")
path_sub_ses <- file.path(dir_dataset, "subjects_sessions.csv")

path_merge <- file.path(
  dir_evolpsy, "go1_files", "pncgo1_data_merge_mar2025.csv"
)

path_env_ses <- file.path(dir_evolpsy, "zac_data", "env_scores.csv")
path_env_trauma <- file.path(dir_evolpsy, "zac_data", "env_for_zac.csv")

path_goassess <- file.path(
  "/", "data", "secure", "bit_repo", "projects_repo", "goassess_scoring",
  "results", "data_score.csv"
)

# Read Data
raw_imaging <- read_csv(path_imaging)
raw_sub_ses <- read_csv(path_sub_ses)

raw_merge <- read_csv(path_merge)

raw_env_ses <- read_csv(path_env_ses)
raw_env_trauma <- read_csv(path_env_trauma)

raw_goassess <- read_csv(path_goassess)
```

```{r}
#| label: clean data
#| include: false
# Demographics
demo <- raw_sub_ses |>
  select(bblid, age) |>
  left_join(
    select(raw_merge, bblid, sex, clinical_goassessDxpmr7),
    by = "bblid"
  ) |>
  rename(dx = clinical_goassessDxpmr7) |>
  mutate(
    age = age / 12,
    dx = str_to_lower(dx),
    sex = factor(
      case_when(sex == 1 ~ "Male", sex == 2 ~ "Female"),
      levels = c("Female", "Male")
    )
  )

# Environment
env <- full_join(raw_env_ses, raw_env_trauma, by = "bblid") |>
  select(bblid, envSES, Trauma_Exposure) |>
  clean_names()

# Imaging
imaging_qc <- raw_sub_ses |>
  mutate(qc = cume_dist(euler)) |>
  filter(qc > 0.01) |>
  select(bblid, scanid)

imaging <- raw_imaging |>
  filter(atlas == "desikan_killiany", !is.na(lobe)) |>
  semi_join(imaging_qc, by = c("bblid", "scanid")) |>
  pivot_wider(values_from = value, names_from = metric) |>
  select(bblid, scanid, laterality, region, lgi, area)

global_lgi <- imaging |>
  group_by(bblid, scanid) |>
  summarize(lgi = weighted.mean(lgi, area), .groups = "drop")

# Clinical
clinical <- raw_merge |>
  select(bblid, starts_with("clinical_longfactor_corrTraits_")) |>
  pivot_longer(cols = -bblid, values_to = "score", names_to = "factor") |>
  mutate(factor = str_replace(factor, "clinical_longfactor_corrTraits_", ""))

# Cognitive
cnb <- raw_merge |>
  select(bblid, starts_with("cnb") & ends_with("efficiency_agereg")) |>
  pivot_longer(cols = -bblid, values_to = "efficiency", names_to = "domain") |>
  mutate(
    domain = str_replace_all(domain, c("cnb_" = "", "_efficiency_agereg" = ""))
  ) |>
  filter(domain != "discounting")

# GOASSESS
goassess <-
  raw_goassess |>
  semi_join(demo, by = c("subject_id" = "bblid")) |>
  filter(version == 1) |>
  group_by(subject_id) |>
  summarize(across(starts_with("smry_"), \(x) max(x, na.rm = TRUE)))
```

# Two-Way Interactions
## Global LGI vs Age
```{r}
#| label: lgi vs age
data_lgi_age <-
  inner_join(global_lgi, demo, by = c("bblid")) |>
  select(lgi, age) |>
  drop_na()

test_lgi_age <-
  cor.test(data_lgi_age$lgi, data_lgi_age$age)

plot_lgi_age <-
  ggplot(data = data_lgi_age, aes(x = age, y = lgi)) +
  geom_point() +
  theme_minimal() +
  labs(
    title = "Correlation of Global LGI and Age",
    subtitle = report_correlation(test_lgi_age),
    x = "Age",
    y = "LGI (global)"
  )

plot_lgi_age

model_lgi_age <- gam(
  lgi ~ age + s(age, m = c(2, 0)),
  data = data_lgi_age,
  method = "REML"
)

summary(model_lgi_age)

plot_lgi_age_linearity <- ggplot(data = data_lgi_age, aes(x = age, y = lgi)) +
  geom_point() +
  geom_smooth(
    method = "lm",
    formula = y ~ x,
    se = FALSE,
    aes(color = "Linear")
  ) +
  geom_smooth(
    method = "gam",
    formula = y ~ s(x),
    se = FALSE,
    aes(color = "Nonlinear")
  ) +
  scale_color_manual(
    values = c("Linear" = "blue", "Nonlinear" = "red"),
    name = NULL
  ) +
  theme_minimal() +
  theme(legend.position = "bottom") +
  labs(
    title = "Linearity of Relationship Between Global LGI and Age",
    x = "Age",
    y = "LGI (global)"
  )

plot_lgi_age_linearity
```

## Global LGI vs Socioeconomic Status
```{r}
#| label: lgi vs ses
data_lgi_ses <-
  inner_join(global_lgi, env, by = "bblid") |>
  select(lgi, env_ses) |>
  drop_na()

test_lgi_ses <-
  cor.test(data_lgi_ses$lgi, data_lgi_ses$env_ses)

plot_lgi_ses <-
  ggplot(data = data_lgi_ses, aes(x = env_ses, y = lgi)) +
  geom_point() +
  theme_minimal() +
  labs(
    title = "Correlation of Global LGI and Socioeconomic Status",
    subtitle = report_correlation(test_lgi_ses),
    x = "Socioeconomic Status",
    y = "LGI (global)"
  )

plot_lgi_ses
```

## Global LGI vs Trauma Exposure
```{r}
#| label: lgi vs trauma
data_lgi_trauma <-
  inner_join(global_lgi, env, by = "bblid") |>
  select(lgi, trauma_exposure) |>
  drop_na()

test_lgi_trauma <-
  cor.test(data_lgi_trauma$lgi, data_lgi_trauma$trauma_exposure)

plot_lgi_trauma <-
  ggplot(data = data_lgi_trauma, aes(x = trauma_exposure, y = lgi)) +
  geom_point() +
  theme_minimal() +
  labs(
    title = "Correlation of Global LGI and Trauma Exposure",
    subtitle = report_correlation(test_lgi_trauma),
    x = "Trauma Exposure",
    y = "LGI (global)"
  )

plot_lgi_trauma
```

## Global LGI vs Sex
```{r}
#| label: lgi vs sex
data_lgi_sex <-
  inner_join(global_lgi, demo, by = "bblid") |>
  select(lgi, sex) |>
  drop_na()

test_lgi_sex <-
  t.test(lgi ~ sex, data = data_lgi_sex)

plot_lgi_sex <-
  ggplot(data = data_lgi_sex, aes(x = sex, y = lgi, color = sex, fill = sex)) +
  geom_jitter(alpha = 0.25) +
  geom_violin(alpha = 0.5) +
  theme_minimal() +
  theme(legend.position = "none") +
  color_scale_sex +
  fill_scale_sex +
  labs(
    title = "Differences in Global LGI between Sexes",
    subtitle = report_t_test(test_lgi_sex),
    x = "Sex",
    y = "LGI (global)"
  )

plot_lgi_sex
```

## Global LGI vs GOASSESS Psychosis Category
```{r}
#| label: lgi vs psy
data_lgi_psy <-
  inner_join(global_lgi, goassess, by = c("bblid" = "subject_id")) |>
  select(lgi, smry_psy_cat) |>
  filter(smry_psy_cat %in% c(0, 1, 2, 3, 4)) |>
  mutate(smry_psy_cat = ordered(smry_psy_cat)) |>
  drop_na()

test_lgi_psy <-
  clinfun::jonckheere.test(
    x = data_lgi_psy$lgi,
    g = data_lgi_psy$smry_psy_cat,
    alternative = "decreasing"
  )

plot_lgi_psy <-
  ggplot(
    data = data_lgi_psy,
    aes(x = smry_psy_cat, y = lgi, color = smry_psy_cat, fill = smry_psy_cat)
  ) +
  geom_jitter(alpha = 0.25) +
  geom_violin(alpha = 0.5) +
  theme_minimal() +
  theme(legend.position = "none") +
  scale_x_discrete(
    labels = c(
      "0" = "Not Endorsed",
      "1" = "Endorsed",
      "2" = "Subthreshold",
      "3" = "Threshold",
      "4" = "Significant"
    )
  ) +
  labs(
    title = "Differences in Global LGI between Psychosis Categories",
    subtitle = report_jt(test_lgi_psy),
    x = "GOASSESS Psychosis Category",
    y = "LGI (global)"
  )

plot_lgi_psy
```